# services:
#   - type: web
#     name: laravel-backend
#     env: docker
#     plan: free
#     region: oregon
#     dockerfilePath: ./Dockerfile
#     buildCommand: ""
#     startCommand: ""
#     healthCheckPath: /
